
# ~/.config/alacritty/alacritty.toml

[terminal.shell]
program = "/opt/homebrew/bin/zellij"


[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "none"
opacity = 0.95
blur = true


[font]
normal = { family = "JetBrains Mono NL", style = "Regular" }
bold = { family = "JetBrains Mono NL", style = "Bold" }
italic = { family = "JetBrains Mono NL", style = "Italic" }
bold_italic = { family = "JetBrains Mono NL", style = "Bold Italic" }
size = 14.5
offset = { x = 1, y = 1 }




[colors.primary]
background = "#15191e"
foreground = "#dbdbdb"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.cursor]
text = "#000000"
cursor = "#fefefe"

[colors.vi_mode_cursor]
text = "#1d2021"
cursor = "#f39d21"

[colors.selection]
text = "#1d2021"
background = "#d5c4a1"

[colors.search.matches]
foreground = "#1d2021"
background = "#fabd2f"

[colors.search.focused_match]
foreground = "#1d2021"
background = "#fe8019"

[colors.footer_bar]
background = "#d65d0e"
foreground = "#1d2021"

